name: Destroy

on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 
    
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::209479268294:role/GithubOIDCRole
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.5
    - name: Terraform Init
      run: terraform init -lock=false
    
    - name: Terraform Destroy
      run: terraform destroy -auto-approve -lock=false
      continue-on-error: true